# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.repocreds_repo_creds_response import RepocredsRepoCredsResponse  # noqa: E501
from argocd.rest import ApiException


class TestRepocredsRepoCredsResponse(unittest.TestCase):
    """RepocredsRepoCredsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepocredsRepoCredsResponse(self):
        """Test RepocredsRepoCredsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.repocreds_repo_creds_response.RepocredsRepoCredsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
