# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_resource_networking_info import V1alpha1ResourceNetworkingInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1ResourceNetworkingInfo(unittest.TestCase):
    """V1alpha1ResourceNetworkingInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ResourceNetworkingInfo(self):
        """Test V1alpha1ResourceNetworkingInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_resource_networking_info.V1alpha1ResourceNetworkingInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
