# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.application_service_api import ApplicationServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationServiceApi(unittest.TestCase):
    """ApplicationServiceApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_application_service_create(self):
        """Test case for application_service_create

        Create creates an application  # noqa: E501
        """
        pass

    def test_application_service_delete(self):
        """Test case for application_service_delete

        Delete deletes an application  # noqa: E501
        """
        pass

    def test_application_service_delete_resource(self):
        """Test case for application_service_delete_resource

        DeleteResource deletes a single application resource  # noqa: E501
        """
        pass

    def test_application_service_get(self):
        """Test case for application_service_get

        Get returns an application by name  # noqa: E501
        """
        pass

    def test_application_service_get_application_sync_windows(self):
        """Test case for application_service_get_application_sync_windows

        Get returns sync windows of the application  # noqa: E501
        """
        pass

    def test_application_service_get_manifests(self):
        """Test case for application_service_get_manifests

        GetManifests returns application manifests  # noqa: E501
        """
        pass

    def test_application_service_get_manifests_with_files(self):
        """Test case for application_service_get_manifests_with_files

        GetManifestsWithFiles returns application manifests using provided files to generate them  # noqa: E501
        """
        pass

    def test_application_service_get_resource(self):
        """Test case for application_service_get_resource

        GetResource returns single application resource  # noqa: E501
        """
        pass

    def test_application_service_list(self):
        """Test case for application_service_list

        List returns list of applications  # noqa: E501
        """
        pass

    def test_application_service_list_links(self):
        """Test case for application_service_list_links

        ListLinks returns the list of all application deep links  # noqa: E501
        """
        pass

    def test_application_service_list_resource_actions(self):
        """Test case for application_service_list_resource_actions

        ListResourceActions returns list of resource actions  # noqa: E501
        """
        pass

    def test_application_service_list_resource_events(self):
        """Test case for application_service_list_resource_events

        ListResourceEvents returns a list of event resources  # noqa: E501
        """
        pass

    def test_application_service_list_resource_links(self):
        """Test case for application_service_list_resource_links

        ListResourceLinks returns the list of all resource deep links  # noqa: E501
        """
        pass

    def test_application_service_managed_resources(self):
        """Test case for application_service_managed_resources

        ManagedResources returns list of managed resources  # noqa: E501
        """
        pass

    def test_application_service_patch(self):
        """Test case for application_service_patch

        Patch patch an application  # noqa: E501
        """
        pass

    def test_application_service_patch_resource(self):
        """Test case for application_service_patch_resource

        PatchResource patch single application resource  # noqa: E501
        """
        pass

    def test_application_service_pod_logs(self):
        """Test case for application_service_pod_logs

        PodLogs returns stream of log entries for the specified pod. Pod  # noqa: E501
        """
        pass

    def test_application_service_pod_logs2(self):
        """Test case for application_service_pod_logs2

        PodLogs returns stream of log entries for the specified pod. Pod  # noqa: E501
        """
        pass

    def test_application_service_resource_tree(self):
        """Test case for application_service_resource_tree

        ResourceTree returns resource tree  # noqa: E501
        """
        pass

    def test_application_service_revision_chart_details(self):
        """Test case for application_service_revision_chart_details

        Get the chart metadata (description, maintainers, home) for a specific revision of the application  # noqa: E501
        """
        pass

    def test_application_service_revision_metadata(self):
        """Test case for application_service_revision_metadata

        Get the meta-data (author, date, tags, message) for a specific revision of the application  # noqa: E501
        """
        pass

    def test_application_service_rollback(self):
        """Test case for application_service_rollback

        Rollback syncs an application to its target state  # noqa: E501
        """
        pass

    def test_application_service_run_resource_action(self):
        """Test case for application_service_run_resource_action

        RunResourceAction run resource action  # noqa: E501
        """
        pass

    def test_application_service_sync(self):
        """Test case for application_service_sync

        Sync syncs an application to its target state  # noqa: E501
        """
        pass

    def test_application_service_terminate_operation(self):
        """Test case for application_service_terminate_operation

        TerminateOperation terminates the currently running operation  # noqa: E501
        """
        pass

    def test_application_service_update(self):
        """Test case for application_service_update

        Update updates an application  # noqa: E501
        """
        pass

    def test_application_service_update_spec(self):
        """Test case for application_service_update_spec

        UpdateSpec updates an application spec  # noqa: E501
        """
        pass

    def test_application_service_watch(self):
        """Test case for application_service_watch

        Watch returns stream of application change events  # noqa: E501
        """
        pass

    def test_application_service_watch_resource_tree(self):
        """Test case for application_service_watch_resource_tree

        Watch returns stream of application resource tree  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
