# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.application_application_rollback_request import ApplicationApplicationRollbackRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationApplicationRollbackRequest(unittest.TestCase):
    """ApplicationApplicationRollbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationApplicationRollbackRequest(self):
        """Test ApplicationApplicationRollbackRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.application_application_rollback_request.ApplicationApplicationRollbackRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
