# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.v1alpha1_helm_parameter import V1alpha1HelmParameter  # noqa: E501
from argocd.rest import ApiException


class TestV1alpha1HelmParameter(unittest.TestCase):
    """V1alpha1HelmParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1HelmParameter(self):
        """Test V1alpha1HelmParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.v1alpha1_helm_parameter.V1alpha1HelmParameter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
