# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.application_operation_terminate_response import ApplicationOperationTerminateResponse  # noqa: E501
from argocd.rest import ApiException


class TestApplicationOperationTerminateResponse(unittest.TestCase):
    """ApplicationOperationTerminateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationOperationTerminateResponse(self):
        """Test ApplicationOperationTerminateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.application_operation_terminate_response.ApplicationOperationTerminateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
