# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_app_project_spec import V1alpha1AppProjectSpec  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1AppProjectSpec(unittest.TestCase):
    """V1alpha1AppProjectSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1AppProjectSpec(self):
        """Test V1alpha1AppProjectSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_app_project_spec.V1alpha1AppProjectSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
