# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1_port_status import V1PortStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestV1PortStatus(unittest.TestCase):
    """V1PortStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1PortStatus(self):
        """Test V1PortStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_port_status.V1PortStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
