# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_signature_key import V1alpha1SignatureKey  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1SignatureKey(unittest.TestCase):
    """V1alpha1SignatureKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SignatureKey(self):
        """Test V1alpha1SignatureKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_signature_key.V1alpha1SignatureKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
