# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.v1_micro_time import V1MicroTime  # noqa: E501
from argocd.rest import ApiException


class TestV1MicroTime(unittest.TestCase):
    """V1MicroTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1MicroTime(self):
        """Test V1MicroTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.v1_micro_time.V1MicroTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
