# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.session_session_response import SessionSessionResponse  # noqa: E501
from argocd.rest import ApiException


class TestSessionSessionResponse(unittest.TestCase):
    """SessionSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionSessionResponse(self):
        """Test SessionSessionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.session_session_response.SessionSessionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
