# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.cluster_google_analytics_config import ClusterGoogleAnalyticsConfig  # noqa: E501
from argocd.rest import ApiException


class TestClusterGoogleAnalyticsConfig(unittest.TestCase):
    """ClusterGoogleAnalyticsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterGoogleAnalyticsConfig(self):
        """Test ClusterGoogleAnalyticsConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.cluster_google_analytics_config.ClusterGoogleAnalyticsConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
