# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.project_project_token_response import ProjectProjectTokenResponse  # noqa: E501
from argocd.rest import ApiException


class TestProjectProjectTokenResponse(unittest.TestCase):
    """ProjectProjectTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectTokenResponse(self):
        """Test ProjectProjectTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.project_project_token_response.ProjectProjectTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
