# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.repository_repo_app_details_query import RepositoryRepoAppDetailsQuery  # noqa: E501
from swagger_client.rest import ApiException


class TestRepositoryRepoAppDetailsQuery(unittest.TestCase):
    """RepositoryRepoAppDetailsQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryRepoAppDetailsQuery(self):
        """Test RepositoryRepoAppDetailsQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.repository_repo_app_details_query.RepositoryRepoAppDetailsQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
