# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.v1alpha1_application_set_nested_generator import V1alpha1ApplicationSetNestedGenerator  # noqa: E501
from argocd.rest import ApiException


class TestV1alpha1ApplicationSetNestedGenerator(unittest.TestCase):
    """V1alpha1ApplicationSetNestedGenerator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSetNestedGenerator(self):
        """Test V1alpha1ApplicationSetNestedGenerator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.v1alpha1_application_set_nested_generator.V1alpha1ApplicationSetNestedGenerator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
