# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.project_project_create_request import ProjectProjectCreateRequest  # noqa: E501
from argocd.rest import ApiException


class TestProjectProjectCreateRequest(unittest.TestCase):
    """ProjectProjectCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectProjectCreateRequest(self):
        """Test ProjectProjectCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.project_project_create_request.ProjectProjectCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
