# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.v1alpha1_application_source_plugin import V1alpha1ApplicationSourcePlugin  # noqa: E501
from argocd.rest import ApiException


class TestV1alpha1ApplicationSourcePlugin(unittest.TestCase):
    """V1alpha1ApplicationSourcePlugin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSourcePlugin(self):
        """Test V1alpha1ApplicationSourcePlugin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.v1alpha1_application_source_plugin.V1alpha1ApplicationSourcePlugin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
