# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_bearer_token_bitbucket_cloud import V1alpha1BearerTokenBitbucketCloud  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1BearerTokenBitbucketCloud(unittest.TestCase):
    """V1alpha1BearerTokenBitbucketCloud unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1BearerTokenBitbucketCloud(self):
        """Test V1alpha1BearerTokenBitbucketCloud"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_bearer_token_bitbucket_cloud.V1alpha1BearerTokenBitbucketCloud()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
