# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.repository_repo_apps_response import RepositoryRepoAppsResponse  # noqa: E501
from argocd.rest import ApiException


class TestRepositoryRepoAppsResponse(unittest.TestCase):
    """RepositoryRepoAppsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryRepoAppsResponse(self):
        """Test RepositoryRepoAppsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.repository_repo_apps_response.RepositoryRepoAppsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
