# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_scm_provider_generator_gitlab import V1alpha1SCMProviderGeneratorGitlab  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1SCMProviderGeneratorGitlab(unittest.TestCase):
    """V1alpha1SCMProviderGeneratorGitlab unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SCMProviderGeneratorGitlab(self):
        """Test V1alpha1SCMProviderGeneratorGitlab"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_scm_provider_generator_gitlab.V1alpha1SCMProviderGeneratorGitlab()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
