# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cluster_help import ClusterHelp  # noqa: E501
from swagger_client.rest import ApiException


class TestClusterHelp(unittest.TestCase):
    """ClusterHelp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterHelp(self):
        """Test ClusterHelp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cluster_help.ClusterHelp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
