# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_application_set_template_meta import V1alpha1ApplicationSetTemplateMeta  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1ApplicationSetTemplateMeta(unittest.TestCase):
    """V1alpha1ApplicationSetTemplateMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ApplicationSetTemplateMeta(self):
        """Test V1alpha1ApplicationSetTemplateMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_application_set_template_meta.V1alpha1ApplicationSetTemplateMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
