# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import argocd
from argocd.models.v1alpha1_gnu_pg_public_key_list import V1alpha1GnuPGPublicKeyList  # noqa: E501
from argocd.rest import ApiException


class TestV1alpha1GnuPGPublicKeyList(unittest.TestCase):
    """V1alpha1GnuPGPublicKeyList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1GnuPGPublicKeyList(self):
        """Test V1alpha1GnuPGPublicKeyList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = argocd.models.v1alpha1_gnu_pg_public_key_list.V1alpha1GnuPGPublicKeyList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
