# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1alpha1_sync_strategy_apply import V1alpha1SyncStrategyApply  # noqa: E501
from swagger_client.rest import ApiException


class TestV1alpha1SyncStrategyApply(unittest.TestCase):
    """V1alpha1SyncStrategyApply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SyncStrategyApply(self):
        """Test V1alpha1SyncStrategyApply"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1alpha1_sync_strategy_apply.V1alpha1SyncStrategyApply()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
