# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "python-argocd"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Python client for ArgoCD",
    author_email="suraj_waragade@live.com",
    url="https://github.com/swaragade/argocd-python",
    keywords=["Swagger", "ArgoCD"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="Python implementation of the ArgoCD API"
)
