# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterSettings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_label_key': 'str',
        'apps_in_any_namespace_enabled': 'bool',
        'config_management_plugins': 'list[V1alpha1ConfigManagementPlugin]',
        'controller_namespace': 'str',
        'dex_config': 'ClusterDexConfig',
        'exec_enabled': 'bool',
        'google_analytics': 'ClusterGoogleAnalyticsConfig',
        'help': 'ClusterHelp',
        'kustomize_options': 'V1alpha1KustomizeOptions',
        'kustomize_versions': 'list[str]',
        'oidc_config': 'ClusterOIDCConfig',
        'password_pattern': 'str',
        'plugins': 'list[ClusterPlugin]',
        'resource_overrides': 'dict(str, V1alpha1ResourceOverride)',
        'status_badge_enabled': 'bool',
        'status_badge_root_url': 'str',
        'tracking_method': 'str',
        'ui_banner_content': 'str',
        'ui_banner_permanent': 'bool',
        'ui_banner_position': 'str',
        'ui_banner_url': 'str',
        'ui_css_url': 'str',
        'url': 'str',
        'user_logins_disabled': 'bool'
    }

    attribute_map = {
        'app_label_key': 'appLabelKey',
        'apps_in_any_namespace_enabled': 'appsInAnyNamespaceEnabled',
        'config_management_plugins': 'configManagementPlugins',
        'controller_namespace': 'controllerNamespace',
        'dex_config': 'dexConfig',
        'exec_enabled': 'execEnabled',
        'google_analytics': 'googleAnalytics',
        'help': 'help',
        'kustomize_options': 'kustomizeOptions',
        'kustomize_versions': 'kustomizeVersions',
        'oidc_config': 'oidcConfig',
        'password_pattern': 'passwordPattern',
        'plugins': 'plugins',
        'resource_overrides': 'resourceOverrides',
        'status_badge_enabled': 'statusBadgeEnabled',
        'status_badge_root_url': 'statusBadgeRootUrl',
        'tracking_method': 'trackingMethod',
        'ui_banner_content': 'uiBannerContent',
        'ui_banner_permanent': 'uiBannerPermanent',
        'ui_banner_position': 'uiBannerPosition',
        'ui_banner_url': 'uiBannerURL',
        'ui_css_url': 'uiCssURL',
        'url': 'url',
        'user_logins_disabled': 'userLoginsDisabled'
    }

    def __init__(self, app_label_key=None, apps_in_any_namespace_enabled=None, config_management_plugins=None, controller_namespace=None, dex_config=None, exec_enabled=None, google_analytics=None, help=None, kustomize_options=None, kustomize_versions=None, oidc_config=None, password_pattern=None, plugins=None, resource_overrides=None, status_badge_enabled=None, status_badge_root_url=None, tracking_method=None, ui_banner_content=None, ui_banner_permanent=None, ui_banner_position=None, ui_banner_url=None, ui_css_url=None, url=None, user_logins_disabled=None):  # noqa: E501
        """ClusterSettings - a model defined in Swagger"""  # noqa: E501
        self._app_label_key = None
        self._apps_in_any_namespace_enabled = None
        self._config_management_plugins = None
        self._controller_namespace = None
        self._dex_config = None
        self._exec_enabled = None
        self._google_analytics = None
        self._help = None
        self._kustomize_options = None
        self._kustomize_versions = None
        self._oidc_config = None
        self._password_pattern = None
        self._plugins = None
        self._resource_overrides = None
        self._status_badge_enabled = None
        self._status_badge_root_url = None
        self._tracking_method = None
        self._ui_banner_content = None
        self._ui_banner_permanent = None
        self._ui_banner_position = None
        self._ui_banner_url = None
        self._ui_css_url = None
        self._url = None
        self._user_logins_disabled = None
        self.discriminator = None
        if app_label_key is not None:
            self.app_label_key = app_label_key
        if apps_in_any_namespace_enabled is not None:
            self.apps_in_any_namespace_enabled = apps_in_any_namespace_enabled
        if config_management_plugins is not None:
            self.config_management_plugins = config_management_plugins
        if controller_namespace is not None:
            self.controller_namespace = controller_namespace
        if dex_config is not None:
            self.dex_config = dex_config
        if exec_enabled is not None:
            self.exec_enabled = exec_enabled
        if google_analytics is not None:
            self.google_analytics = google_analytics
        if help is not None:
            self.help = help
        if kustomize_options is not None:
            self.kustomize_options = kustomize_options
        if kustomize_versions is not None:
            self.kustomize_versions = kustomize_versions
        if oidc_config is not None:
            self.oidc_config = oidc_config
        if password_pattern is not None:
            self.password_pattern = password_pattern
        if plugins is not None:
            self.plugins = plugins
        if resource_overrides is not None:
            self.resource_overrides = resource_overrides
        if status_badge_enabled is not None:
            self.status_badge_enabled = status_badge_enabled
        if status_badge_root_url is not None:
            self.status_badge_root_url = status_badge_root_url
        if tracking_method is not None:
            self.tracking_method = tracking_method
        if ui_banner_content is not None:
            self.ui_banner_content = ui_banner_content
        if ui_banner_permanent is not None:
            self.ui_banner_permanent = ui_banner_permanent
        if ui_banner_position is not None:
            self.ui_banner_position = ui_banner_position
        if ui_banner_url is not None:
            self.ui_banner_url = ui_banner_url
        if ui_css_url is not None:
            self.ui_css_url = ui_css_url
        if url is not None:
            self.url = url
        if user_logins_disabled is not None:
            self.user_logins_disabled = user_logins_disabled

    @property
    def app_label_key(self):
        """Gets the app_label_key of this ClusterSettings.  # noqa: E501


        :return: The app_label_key of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._app_label_key

    @app_label_key.setter
    def app_label_key(self, app_label_key):
        """Sets the app_label_key of this ClusterSettings.


        :param app_label_key: The app_label_key of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._app_label_key = app_label_key

    @property
    def apps_in_any_namespace_enabled(self):
        """Gets the apps_in_any_namespace_enabled of this ClusterSettings.  # noqa: E501


        :return: The apps_in_any_namespace_enabled of this ClusterSettings.  # noqa: E501
        :rtype: bool
        """
        return self._apps_in_any_namespace_enabled

    @apps_in_any_namespace_enabled.setter
    def apps_in_any_namespace_enabled(self, apps_in_any_namespace_enabled):
        """Sets the apps_in_any_namespace_enabled of this ClusterSettings.


        :param apps_in_any_namespace_enabled: The apps_in_any_namespace_enabled of this ClusterSettings.  # noqa: E501
        :type: bool
        """

        self._apps_in_any_namespace_enabled = apps_in_any_namespace_enabled

    @property
    def config_management_plugins(self):
        """Gets the config_management_plugins of this ClusterSettings.  # noqa: E501

        Deprecated: use sidecar plugins instead.  # noqa: E501

        :return: The config_management_plugins of this ClusterSettings.  # noqa: E501
        :rtype: list[V1alpha1ConfigManagementPlugin]
        """
        return self._config_management_plugins

    @config_management_plugins.setter
    def config_management_plugins(self, config_management_plugins):
        """Sets the config_management_plugins of this ClusterSettings.

        Deprecated: use sidecar plugins instead.  # noqa: E501

        :param config_management_plugins: The config_management_plugins of this ClusterSettings.  # noqa: E501
        :type: list[V1alpha1ConfigManagementPlugin]
        """

        self._config_management_plugins = config_management_plugins

    @property
    def controller_namespace(self):
        """Gets the controller_namespace of this ClusterSettings.  # noqa: E501


        :return: The controller_namespace of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._controller_namespace

    @controller_namespace.setter
    def controller_namespace(self, controller_namespace):
        """Sets the controller_namespace of this ClusterSettings.


        :param controller_namespace: The controller_namespace of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._controller_namespace = controller_namespace

    @property
    def dex_config(self):
        """Gets the dex_config of this ClusterSettings.  # noqa: E501


        :return: The dex_config of this ClusterSettings.  # noqa: E501
        :rtype: ClusterDexConfig
        """
        return self._dex_config

    @dex_config.setter
    def dex_config(self, dex_config):
        """Sets the dex_config of this ClusterSettings.


        :param dex_config: The dex_config of this ClusterSettings.  # noqa: E501
        :type: ClusterDexConfig
        """

        self._dex_config = dex_config

    @property
    def exec_enabled(self):
        """Gets the exec_enabled of this ClusterSettings.  # noqa: E501


        :return: The exec_enabled of this ClusterSettings.  # noqa: E501
        :rtype: bool
        """
        return self._exec_enabled

    @exec_enabled.setter
    def exec_enabled(self, exec_enabled):
        """Sets the exec_enabled of this ClusterSettings.


        :param exec_enabled: The exec_enabled of this ClusterSettings.  # noqa: E501
        :type: bool
        """

        self._exec_enabled = exec_enabled

    @property
    def google_analytics(self):
        """Gets the google_analytics of this ClusterSettings.  # noqa: E501


        :return: The google_analytics of this ClusterSettings.  # noqa: E501
        :rtype: ClusterGoogleAnalyticsConfig
        """
        return self._google_analytics

    @google_analytics.setter
    def google_analytics(self, google_analytics):
        """Sets the google_analytics of this ClusterSettings.


        :param google_analytics: The google_analytics of this ClusterSettings.  # noqa: E501
        :type: ClusterGoogleAnalyticsConfig
        """

        self._google_analytics = google_analytics

    @property
    def help(self):
        """Gets the help of this ClusterSettings.  # noqa: E501


        :return: The help of this ClusterSettings.  # noqa: E501
        :rtype: ClusterHelp
        """
        return self._help

    @help.setter
    def help(self, help):
        """Sets the help of this ClusterSettings.


        :param help: The help of this ClusterSettings.  # noqa: E501
        :type: ClusterHelp
        """

        self._help = help

    @property
    def kustomize_options(self):
        """Gets the kustomize_options of this ClusterSettings.  # noqa: E501


        :return: The kustomize_options of this ClusterSettings.  # noqa: E501
        :rtype: V1alpha1KustomizeOptions
        """
        return self._kustomize_options

    @kustomize_options.setter
    def kustomize_options(self, kustomize_options):
        """Sets the kustomize_options of this ClusterSettings.


        :param kustomize_options: The kustomize_options of this ClusterSettings.  # noqa: E501
        :type: V1alpha1KustomizeOptions
        """

        self._kustomize_options = kustomize_options

    @property
    def kustomize_versions(self):
        """Gets the kustomize_versions of this ClusterSettings.  # noqa: E501


        :return: The kustomize_versions of this ClusterSettings.  # noqa: E501
        :rtype: list[str]
        """
        return self._kustomize_versions

    @kustomize_versions.setter
    def kustomize_versions(self, kustomize_versions):
        """Sets the kustomize_versions of this ClusterSettings.


        :param kustomize_versions: The kustomize_versions of this ClusterSettings.  # noqa: E501
        :type: list[str]
        """

        self._kustomize_versions = kustomize_versions

    @property
    def oidc_config(self):
        """Gets the oidc_config of this ClusterSettings.  # noqa: E501


        :return: The oidc_config of this ClusterSettings.  # noqa: E501
        :rtype: ClusterOIDCConfig
        """
        return self._oidc_config

    @oidc_config.setter
    def oidc_config(self, oidc_config):
        """Sets the oidc_config of this ClusterSettings.


        :param oidc_config: The oidc_config of this ClusterSettings.  # noqa: E501
        :type: ClusterOIDCConfig
        """

        self._oidc_config = oidc_config

    @property
    def password_pattern(self):
        """Gets the password_pattern of this ClusterSettings.  # noqa: E501


        :return: The password_pattern of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._password_pattern

    @password_pattern.setter
    def password_pattern(self, password_pattern):
        """Sets the password_pattern of this ClusterSettings.


        :param password_pattern: The password_pattern of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._password_pattern = password_pattern

    @property
    def plugins(self):
        """Gets the plugins of this ClusterSettings.  # noqa: E501


        :return: The plugins of this ClusterSettings.  # noqa: E501
        :rtype: list[ClusterPlugin]
        """
        return self._plugins

    @plugins.setter
    def plugins(self, plugins):
        """Sets the plugins of this ClusterSettings.


        :param plugins: The plugins of this ClusterSettings.  # noqa: E501
        :type: list[ClusterPlugin]
        """

        self._plugins = plugins

    @property
    def resource_overrides(self):
        """Gets the resource_overrides of this ClusterSettings.  # noqa: E501


        :return: The resource_overrides of this ClusterSettings.  # noqa: E501
        :rtype: dict(str, V1alpha1ResourceOverride)
        """
        return self._resource_overrides

    @resource_overrides.setter
    def resource_overrides(self, resource_overrides):
        """Sets the resource_overrides of this ClusterSettings.


        :param resource_overrides: The resource_overrides of this ClusterSettings.  # noqa: E501
        :type: dict(str, V1alpha1ResourceOverride)
        """

        self._resource_overrides = resource_overrides

    @property
    def status_badge_enabled(self):
        """Gets the status_badge_enabled of this ClusterSettings.  # noqa: E501


        :return: The status_badge_enabled of this ClusterSettings.  # noqa: E501
        :rtype: bool
        """
        return self._status_badge_enabled

    @status_badge_enabled.setter
    def status_badge_enabled(self, status_badge_enabled):
        """Sets the status_badge_enabled of this ClusterSettings.


        :param status_badge_enabled: The status_badge_enabled of this ClusterSettings.  # noqa: E501
        :type: bool
        """

        self._status_badge_enabled = status_badge_enabled

    @property
    def status_badge_root_url(self):
        """Gets the status_badge_root_url of this ClusterSettings.  # noqa: E501


        :return: The status_badge_root_url of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._status_badge_root_url

    @status_badge_root_url.setter
    def status_badge_root_url(self, status_badge_root_url):
        """Sets the status_badge_root_url of this ClusterSettings.


        :param status_badge_root_url: The status_badge_root_url of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._status_badge_root_url = status_badge_root_url

    @property
    def tracking_method(self):
        """Gets the tracking_method of this ClusterSettings.  # noqa: E501


        :return: The tracking_method of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._tracking_method

    @tracking_method.setter
    def tracking_method(self, tracking_method):
        """Sets the tracking_method of this ClusterSettings.


        :param tracking_method: The tracking_method of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._tracking_method = tracking_method

    @property
    def ui_banner_content(self):
        """Gets the ui_banner_content of this ClusterSettings.  # noqa: E501


        :return: The ui_banner_content of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._ui_banner_content

    @ui_banner_content.setter
    def ui_banner_content(self, ui_banner_content):
        """Sets the ui_banner_content of this ClusterSettings.


        :param ui_banner_content: The ui_banner_content of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._ui_banner_content = ui_banner_content

    @property
    def ui_banner_permanent(self):
        """Gets the ui_banner_permanent of this ClusterSettings.  # noqa: E501


        :return: The ui_banner_permanent of this ClusterSettings.  # noqa: E501
        :rtype: bool
        """
        return self._ui_banner_permanent

    @ui_banner_permanent.setter
    def ui_banner_permanent(self, ui_banner_permanent):
        """Sets the ui_banner_permanent of this ClusterSettings.


        :param ui_banner_permanent: The ui_banner_permanent of this ClusterSettings.  # noqa: E501
        :type: bool
        """

        self._ui_banner_permanent = ui_banner_permanent

    @property
    def ui_banner_position(self):
        """Gets the ui_banner_position of this ClusterSettings.  # noqa: E501


        :return: The ui_banner_position of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._ui_banner_position

    @ui_banner_position.setter
    def ui_banner_position(self, ui_banner_position):
        """Sets the ui_banner_position of this ClusterSettings.


        :param ui_banner_position: The ui_banner_position of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._ui_banner_position = ui_banner_position

    @property
    def ui_banner_url(self):
        """Gets the ui_banner_url of this ClusterSettings.  # noqa: E501


        :return: The ui_banner_url of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._ui_banner_url

    @ui_banner_url.setter
    def ui_banner_url(self, ui_banner_url):
        """Sets the ui_banner_url of this ClusterSettings.


        :param ui_banner_url: The ui_banner_url of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._ui_banner_url = ui_banner_url

    @property
    def ui_css_url(self):
        """Gets the ui_css_url of this ClusterSettings.  # noqa: E501


        :return: The ui_css_url of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._ui_css_url

    @ui_css_url.setter
    def ui_css_url(self, ui_css_url):
        """Sets the ui_css_url of this ClusterSettings.


        :param ui_css_url: The ui_css_url of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._ui_css_url = ui_css_url

    @property
    def url(self):
        """Gets the url of this ClusterSettings.  # noqa: E501


        :return: The url of this ClusterSettings.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ClusterSettings.


        :param url: The url of this ClusterSettings.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def user_logins_disabled(self):
        """Gets the user_logins_disabled of this ClusterSettings.  # noqa: E501


        :return: The user_logins_disabled of this ClusterSettings.  # noqa: E501
        :rtype: bool
        """
        return self._user_logins_disabled

    @user_logins_disabled.setter
    def user_logins_disabled(self, user_logins_disabled):
        """Sets the user_logins_disabled of this ClusterSettings.


        :param user_logins_disabled: The user_logins_disabled of this ClusterSettings.  # noqa: E501
        :type: bool
        """

        self._user_logins_disabled = user_logins_disabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterSettings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
