# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterHelp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'binary_urls': 'dict(str, str)',
        'chat_text': 'str',
        'chat_url': 'str'
    }

    attribute_map = {
        'binary_urls': 'binaryUrls',
        'chat_text': 'chatText',
        'chat_url': 'chatUrl'
    }

    def __init__(self, binary_urls=None, chat_text=None, chat_url=None):  # noqa: E501
        """ClusterHelp - a model defined in Swagger"""  # noqa: E501
        self._binary_urls = None
        self._chat_text = None
        self._chat_url = None
        self.discriminator = None
        if binary_urls is not None:
            self.binary_urls = binary_urls
        if chat_text is not None:
            self.chat_text = chat_text
        if chat_url is not None:
            self.chat_url = chat_url

    @property
    def binary_urls(self):
        """Gets the binary_urls of this ClusterHelp.  # noqa: E501


        :return: The binary_urls of this ClusterHelp.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._binary_urls

    @binary_urls.setter
    def binary_urls(self, binary_urls):
        """Sets the binary_urls of this ClusterHelp.


        :param binary_urls: The binary_urls of this ClusterHelp.  # noqa: E501
        :type: dict(str, str)
        """

        self._binary_urls = binary_urls

    @property
    def chat_text(self):
        """Gets the chat_text of this ClusterHelp.  # noqa: E501


        :return: The chat_text of this ClusterHelp.  # noqa: E501
        :rtype: str
        """
        return self._chat_text

    @chat_text.setter
    def chat_text(self, chat_text):
        """Sets the chat_text of this ClusterHelp.


        :param chat_text: The chat_text of this ClusterHelp.  # noqa: E501
        :type: str
        """

        self._chat_text = chat_text

    @property
    def chat_url(self):
        """Gets the chat_url of this ClusterHelp.  # noqa: E501


        :return: The chat_url of this ClusterHelp.  # noqa: E501
        :rtype: str
        """
        return self._chat_url

    @chat_url.setter
    def chat_url(self, chat_url):
        """Sets the chat_url of this ClusterHelp.


        :param chat_url: The chat_url of this ClusterHelp.  # noqa: E501
        :type: str
        """

        self._chat_url = chat_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterHelp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterHelp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
