# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RepositoryHelmAppSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_parameters': 'list[V1alpha1HelmFileParameter]',
        'name': 'str',
        'parameters': 'list[V1alpha1HelmParameter]',
        'value_files': 'list[str]',
        'values': 'str'
    }

    attribute_map = {
        'file_parameters': 'fileParameters',
        'name': 'name',
        'parameters': 'parameters',
        'value_files': 'valueFiles',
        'values': 'values'
    }

    def __init__(self, file_parameters=None, name=None, parameters=None, value_files=None, values=None):  # noqa: E501
        """RepositoryHelmAppSpec - a model defined in Swagger"""  # noqa: E501
        self._file_parameters = None
        self._name = None
        self._parameters = None
        self._value_files = None
        self._values = None
        self.discriminator = None
        if file_parameters is not None:
            self.file_parameters = file_parameters
        if name is not None:
            self.name = name
        if parameters is not None:
            self.parameters = parameters
        if value_files is not None:
            self.value_files = value_files
        if values is not None:
            self.values = values

    @property
    def file_parameters(self):
        """Gets the file_parameters of this RepositoryHelmAppSpec.  # noqa: E501


        :return: The file_parameters of this RepositoryHelmAppSpec.  # noqa: E501
        :rtype: list[V1alpha1HelmFileParameter]
        """
        return self._file_parameters

    @file_parameters.setter
    def file_parameters(self, file_parameters):
        """Sets the file_parameters of this RepositoryHelmAppSpec.


        :param file_parameters: The file_parameters of this RepositoryHelmAppSpec.  # noqa: E501
        :type: list[V1alpha1HelmFileParameter]
        """

        self._file_parameters = file_parameters

    @property
    def name(self):
        """Gets the name of this RepositoryHelmAppSpec.  # noqa: E501


        :return: The name of this RepositoryHelmAppSpec.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RepositoryHelmAppSpec.


        :param name: The name of this RepositoryHelmAppSpec.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parameters(self):
        """Gets the parameters of this RepositoryHelmAppSpec.  # noqa: E501


        :return: The parameters of this RepositoryHelmAppSpec.  # noqa: E501
        :rtype: list[V1alpha1HelmParameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this RepositoryHelmAppSpec.


        :param parameters: The parameters of this RepositoryHelmAppSpec.  # noqa: E501
        :type: list[V1alpha1HelmParameter]
        """

        self._parameters = parameters

    @property
    def value_files(self):
        """Gets the value_files of this RepositoryHelmAppSpec.  # noqa: E501


        :return: The value_files of this RepositoryHelmAppSpec.  # noqa: E501
        :rtype: list[str]
        """
        return self._value_files

    @value_files.setter
    def value_files(self, value_files):
        """Sets the value_files of this RepositoryHelmAppSpec.


        :param value_files: The value_files of this RepositoryHelmAppSpec.  # noqa: E501
        :type: list[str]
        """

        self._value_files = value_files

    @property
    def values(self):
        """Gets the values of this RepositoryHelmAppSpec.  # noqa: E501


        :return: The values of this RepositoryHelmAppSpec.  # noqa: E501
        :rtype: str
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this RepositoryHelmAppSpec.


        :param values: The values of this RepositoryHelmAppSpec.  # noqa: E501
        :type: str
        """

        self._values = values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RepositoryHelmAppSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RepositoryHelmAppSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
