# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1SCMProviderGeneratorAzureDevOps(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_token_ref': 'V1alpha1SecretRef',
        'all_branches': 'bool',
        'api': 'str',
        'organization': 'str',
        'team_project': 'str'
    }

    attribute_map = {
        'access_token_ref': 'accessTokenRef',
        'all_branches': 'allBranches',
        'api': 'api',
        'organization': 'organization',
        'team_project': 'teamProject'
    }

    def __init__(self, access_token_ref=None, all_branches=None, api=None, organization=None, team_project=None):  # noqa: E501
        """V1alpha1SCMProviderGeneratorAzureDevOps - a model defined in Swagger"""  # noqa: E501
        self._access_token_ref = None
        self._all_branches = None
        self._api = None
        self._organization = None
        self._team_project = None
        self.discriminator = None
        if access_token_ref is not None:
            self.access_token_ref = access_token_ref
        if all_branches is not None:
            self.all_branches = all_branches
        if api is not None:
            self.api = api
        if organization is not None:
            self.organization = organization
        if team_project is not None:
            self.team_project = team_project

    @property
    def access_token_ref(self):
        """Gets the access_token_ref of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501


        :return: The access_token_ref of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :rtype: V1alpha1SecretRef
        """
        return self._access_token_ref

    @access_token_ref.setter
    def access_token_ref(self, access_token_ref):
        """Sets the access_token_ref of this V1alpha1SCMProviderGeneratorAzureDevOps.


        :param access_token_ref: The access_token_ref of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :type: V1alpha1SecretRef
        """

        self._access_token_ref = access_token_ref

    @property
    def all_branches(self):
        """Gets the all_branches of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501

        Scan all branches instead of just the default branch.  # noqa: E501

        :return: The all_branches of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :rtype: bool
        """
        return self._all_branches

    @all_branches.setter
    def all_branches(self, all_branches):
        """Sets the all_branches of this V1alpha1SCMProviderGeneratorAzureDevOps.

        Scan all branches instead of just the default branch.  # noqa: E501

        :param all_branches: The all_branches of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :type: bool
        """

        self._all_branches = all_branches

    @property
    def api(self):
        """Gets the api of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501

        The URL to Azure DevOps. If blank, use https://dev.azure.com.  # noqa: E501

        :return: The api of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :rtype: str
        """
        return self._api

    @api.setter
    def api(self, api):
        """Sets the api of this V1alpha1SCMProviderGeneratorAzureDevOps.

        The URL to Azure DevOps. If blank, use https://dev.azure.com.  # noqa: E501

        :param api: The api of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :type: str
        """

        self._api = api

    @property
    def organization(self):
        """Gets the organization of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501

        Azure Devops organization. Required. E.g. \"my-organization\".  # noqa: E501

        :return: The organization of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :rtype: str
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this V1alpha1SCMProviderGeneratorAzureDevOps.

        Azure Devops organization. Required. E.g. \"my-organization\".  # noqa: E501

        :param organization: The organization of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :type: str
        """

        self._organization = organization

    @property
    def team_project(self):
        """Gets the team_project of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501

        Azure Devops team project. Required. E.g. \"my-team\".  # noqa: E501

        :return: The team_project of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :rtype: str
        """
        return self._team_project

    @team_project.setter
    def team_project(self, team_project):
        """Sets the team_project of this V1alpha1SCMProviderGeneratorAzureDevOps.

        Azure Devops team project. Required. E.g. \"my-team\".  # noqa: E501

        :param team_project: The team_project of this V1alpha1SCMProviderGeneratorAzureDevOps.  # noqa: E501
        :type: str
        """

        self._team_project = team_project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1SCMProviderGeneratorAzureDevOps, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1SCMProviderGeneratorAzureDevOps):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
