# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1ApplicationSourceDirectory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'exclude': 'str',
        'include': 'str',
        'jsonnet': 'V1alpha1ApplicationSourceJsonnet',
        'recurse': 'bool'
    }

    attribute_map = {
        'exclude': 'exclude',
        'include': 'include',
        'jsonnet': 'jsonnet',
        'recurse': 'recurse'
    }

    def __init__(self, exclude=None, include=None, jsonnet=None, recurse=None):  # noqa: E501
        """V1alpha1ApplicationSourceDirectory - a model defined in Swagger"""  # noqa: E501
        self._exclude = None
        self._include = None
        self._jsonnet = None
        self._recurse = None
        self.discriminator = None
        if exclude is not None:
            self.exclude = exclude
        if include is not None:
            self.include = include
        if jsonnet is not None:
            self.jsonnet = jsonnet
        if recurse is not None:
            self.recurse = recurse

    @property
    def exclude(self):
        """Gets the exclude of this V1alpha1ApplicationSourceDirectory.  # noqa: E501


        :return: The exclude of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :rtype: str
        """
        return self._exclude

    @exclude.setter
    def exclude(self, exclude):
        """Sets the exclude of this V1alpha1ApplicationSourceDirectory.


        :param exclude: The exclude of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :type: str
        """

        self._exclude = exclude

    @property
    def include(self):
        """Gets the include of this V1alpha1ApplicationSourceDirectory.  # noqa: E501


        :return: The include of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :rtype: str
        """
        return self._include

    @include.setter
    def include(self, include):
        """Sets the include of this V1alpha1ApplicationSourceDirectory.


        :param include: The include of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :type: str
        """

        self._include = include

    @property
    def jsonnet(self):
        """Gets the jsonnet of this V1alpha1ApplicationSourceDirectory.  # noqa: E501


        :return: The jsonnet of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :rtype: V1alpha1ApplicationSourceJsonnet
        """
        return self._jsonnet

    @jsonnet.setter
    def jsonnet(self, jsonnet):
        """Sets the jsonnet of this V1alpha1ApplicationSourceDirectory.


        :param jsonnet: The jsonnet of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :type: V1alpha1ApplicationSourceJsonnet
        """

        self._jsonnet = jsonnet

    @property
    def recurse(self):
        """Gets the recurse of this V1alpha1ApplicationSourceDirectory.  # noqa: E501


        :return: The recurse of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :rtype: bool
        """
        return self._recurse

    @recurse.setter
    def recurse(self, recurse):
        """Sets the recurse of this V1alpha1ApplicationSourceDirectory.


        :param recurse: The recurse of this V1alpha1ApplicationSourceDirectory.  # noqa: E501
        :type: bool
        """

        self._recurse = recurse

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1ApplicationSourceDirectory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ApplicationSourceDirectory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
