# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1RevisionHistory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'deploy_started_at': 'V1Time',
        'deployed_at': 'V1Time',
        'id': 'int',
        'initiated_by': 'V1alpha1OperationInitiator',
        'revision': 'str',
        'revisions': 'list[str]',
        'source': 'V1alpha1ApplicationSource',
        'sources': 'list[V1alpha1ApplicationSource]'
    }

    attribute_map = {
        'deploy_started_at': 'deployStartedAt',
        'deployed_at': 'deployedAt',
        'id': 'id',
        'initiated_by': 'initiatedBy',
        'revision': 'revision',
        'revisions': 'revisions',
        'source': 'source',
        'sources': 'sources'
    }

    def __init__(self, deploy_started_at=None, deployed_at=None, id=None, initiated_by=None, revision=None, revisions=None, source=None, sources=None):  # noqa: E501
        """V1alpha1RevisionHistory - a model defined in Swagger"""  # noqa: E501
        self._deploy_started_at = None
        self._deployed_at = None
        self._id = None
        self._initiated_by = None
        self._revision = None
        self._revisions = None
        self._source = None
        self._sources = None
        self.discriminator = None
        if deploy_started_at is not None:
            self.deploy_started_at = deploy_started_at
        if deployed_at is not None:
            self.deployed_at = deployed_at
        if id is not None:
            self.id = id
        if initiated_by is not None:
            self.initiated_by = initiated_by
        if revision is not None:
            self.revision = revision
        if revisions is not None:
            self.revisions = revisions
        if source is not None:
            self.source = source
        if sources is not None:
            self.sources = sources

    @property
    def deploy_started_at(self):
        """Gets the deploy_started_at of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The deploy_started_at of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1Time
        """
        return self._deploy_started_at

    @deploy_started_at.setter
    def deploy_started_at(self, deploy_started_at):
        """Sets the deploy_started_at of this V1alpha1RevisionHistory.


        :param deploy_started_at: The deploy_started_at of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1Time
        """

        self._deploy_started_at = deploy_started_at

    @property
    def deployed_at(self):
        """Gets the deployed_at of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The deployed_at of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1Time
        """
        return self._deployed_at

    @deployed_at.setter
    def deployed_at(self, deployed_at):
        """Sets the deployed_at of this V1alpha1RevisionHistory.


        :param deployed_at: The deployed_at of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1Time
        """

        self._deployed_at = deployed_at

    @property
    def id(self):
        """Gets the id of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The id of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1alpha1RevisionHistory.


        :param id: The id of this V1alpha1RevisionHistory.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def initiated_by(self):
        """Gets the initiated_by of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The initiated_by of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1alpha1OperationInitiator
        """
        return self._initiated_by

    @initiated_by.setter
    def initiated_by(self, initiated_by):
        """Sets the initiated_by of this V1alpha1RevisionHistory.


        :param initiated_by: The initiated_by of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1alpha1OperationInitiator
        """

        self._initiated_by = initiated_by

    @property
    def revision(self):
        """Gets the revision of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The revision of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """Sets the revision of this V1alpha1RevisionHistory.


        :param revision: The revision of this V1alpha1RevisionHistory.  # noqa: E501
        :type: str
        """

        self._revision = revision

    @property
    def revisions(self):
        """Gets the revisions of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The revisions of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: list[str]
        """
        return self._revisions

    @revisions.setter
    def revisions(self, revisions):
        """Sets the revisions of this V1alpha1RevisionHistory.


        :param revisions: The revisions of this V1alpha1RevisionHistory.  # noqa: E501
        :type: list[str]
        """

        self._revisions = revisions

    @property
    def source(self):
        """Gets the source of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The source of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: V1alpha1ApplicationSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this V1alpha1RevisionHistory.


        :param source: The source of this V1alpha1RevisionHistory.  # noqa: E501
        :type: V1alpha1ApplicationSource
        """

        self._source = source

    @property
    def sources(self):
        """Gets the sources of this V1alpha1RevisionHistory.  # noqa: E501


        :return: The sources of this V1alpha1RevisionHistory.  # noqa: E501
        :rtype: list[V1alpha1ApplicationSource]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this V1alpha1RevisionHistory.


        :param sources: The sources of this V1alpha1RevisionHistory.  # noqa: E501
        :type: list[V1alpha1ApplicationSource]
        """

        self._sources = sources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1RevisionHistory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1RevisionHistory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
