# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1KustomizePatch(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'options': 'dict(str, bool)',
        'patch': 'str',
        'path': 'str',
        'target': 'V1alpha1KustomizeSelector'
    }

    attribute_map = {
        'options': 'options',
        'patch': 'patch',
        'path': 'path',
        'target': 'target'
    }

    def __init__(self, options=None, patch=None, path=None, target=None):  # noqa: E501
        """V1alpha1KustomizePatch - a model defined in Swagger"""  # noqa: E501
        self._options = None
        self._patch = None
        self._path = None
        self._target = None
        self.discriminator = None
        if options is not None:
            self.options = options
        if patch is not None:
            self.patch = patch
        if path is not None:
            self.path = path
        if target is not None:
            self.target = target

    @property
    def options(self):
        """Gets the options of this V1alpha1KustomizePatch.  # noqa: E501


        :return: The options of this V1alpha1KustomizePatch.  # noqa: E501
        :rtype: dict(str, bool)
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this V1alpha1KustomizePatch.


        :param options: The options of this V1alpha1KustomizePatch.  # noqa: E501
        :type: dict(str, bool)
        """

        self._options = options

    @property
    def patch(self):
        """Gets the patch of this V1alpha1KustomizePatch.  # noqa: E501


        :return: The patch of this V1alpha1KustomizePatch.  # noqa: E501
        :rtype: str
        """
        return self._patch

    @patch.setter
    def patch(self, patch):
        """Sets the patch of this V1alpha1KustomizePatch.


        :param patch: The patch of this V1alpha1KustomizePatch.  # noqa: E501
        :type: str
        """

        self._patch = patch

    @property
    def path(self):
        """Gets the path of this V1alpha1KustomizePatch.  # noqa: E501


        :return: The path of this V1alpha1KustomizePatch.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this V1alpha1KustomizePatch.


        :param path: The path of this V1alpha1KustomizePatch.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def target(self):
        """Gets the target of this V1alpha1KustomizePatch.  # noqa: E501


        :return: The target of this V1alpha1KustomizePatch.  # noqa: E501
        :rtype: V1alpha1KustomizeSelector
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this V1alpha1KustomizePatch.


        :param target: The target of this V1alpha1KustomizePatch.  # noqa: E501
        :type: V1alpha1KustomizeSelector
        """

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1KustomizePatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1KustomizePatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
