# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1RevisionMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'author': 'str',
        '_date': 'V1Time',
        'message': 'str',
        'signature_info': 'str',
        'tags': 'list[str]'
    }

    attribute_map = {
        'author': 'author',
        '_date': 'date',
        'message': 'message',
        'signature_info': 'signatureInfo',
        'tags': 'tags'
    }

    def __init__(self, author=None, _date=None, message=None, signature_info=None, tags=None):  # noqa: E501
        """V1alpha1RevisionMetadata - a model defined in Swagger"""  # noqa: E501
        self._author = None
        self.__date = None
        self._message = None
        self._signature_info = None
        self._tags = None
        self.discriminator = None
        if author is not None:
            self.author = author
        if _date is not None:
            self._date = _date
        if message is not None:
            self.message = message
        if signature_info is not None:
            self.signature_info = signature_info
        if tags is not None:
            self.tags = tags

    @property
    def author(self):
        """Gets the author of this V1alpha1RevisionMetadata.  # noqa: E501


        :return: The author of this V1alpha1RevisionMetadata.  # noqa: E501
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this V1alpha1RevisionMetadata.


        :param author: The author of this V1alpha1RevisionMetadata.  # noqa: E501
        :type: str
        """

        self._author = author

    @property
    def _date(self):
        """Gets the _date of this V1alpha1RevisionMetadata.  # noqa: E501


        :return: The _date of this V1alpha1RevisionMetadata.  # noqa: E501
        :rtype: V1Time
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this V1alpha1RevisionMetadata.


        :param _date: The _date of this V1alpha1RevisionMetadata.  # noqa: E501
        :type: V1Time
        """

        self.__date = _date

    @property
    def message(self):
        """Gets the message of this V1alpha1RevisionMetadata.  # noqa: E501

        Message contains the message associated with the revision, most likely the commit message.  # noqa: E501

        :return: The message of this V1alpha1RevisionMetadata.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this V1alpha1RevisionMetadata.

        Message contains the message associated with the revision, most likely the commit message.  # noqa: E501

        :param message: The message of this V1alpha1RevisionMetadata.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def signature_info(self):
        """Gets the signature_info of this V1alpha1RevisionMetadata.  # noqa: E501

        SignatureInfo contains a hint on the signer if the revision was signed with GPG, and signature verification is enabled.  # noqa: E501

        :return: The signature_info of this V1alpha1RevisionMetadata.  # noqa: E501
        :rtype: str
        """
        return self._signature_info

    @signature_info.setter
    def signature_info(self, signature_info):
        """Sets the signature_info of this V1alpha1RevisionMetadata.

        SignatureInfo contains a hint on the signer if the revision was signed with GPG, and signature verification is enabled.  # noqa: E501

        :param signature_info: The signature_info of this V1alpha1RevisionMetadata.  # noqa: E501
        :type: str
        """

        self._signature_info = signature_info

    @property
    def tags(self):
        """Gets the tags of this V1alpha1RevisionMetadata.  # noqa: E501


        :return: The tags of this V1alpha1RevisionMetadata.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this V1alpha1RevisionMetadata.


        :param tags: The tags of this V1alpha1RevisionMetadata.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1RevisionMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1RevisionMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
