# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1ClusterConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aws_auth_config': 'V1alpha1AWSAuthConfig',
        'bearer_token': 'str',
        'exec_provider_config': 'V1alpha1ExecProviderConfig',
        'password': 'str',
        'tls_client_config': 'V1alpha1TLSClientConfig',
        'username': 'str'
    }

    attribute_map = {
        'aws_auth_config': 'awsAuthConfig',
        'bearer_token': 'bearerToken',
        'exec_provider_config': 'execProviderConfig',
        'password': 'password',
        'tls_client_config': 'tlsClientConfig',
        'username': 'username'
    }

    def __init__(self, aws_auth_config=None, bearer_token=None, exec_provider_config=None, password=None, tls_client_config=None, username=None):  # noqa: E501
        """V1alpha1ClusterConfig - a model defined in Swagger"""  # noqa: E501
        self._aws_auth_config = None
        self._bearer_token = None
        self._exec_provider_config = None
        self._password = None
        self._tls_client_config = None
        self._username = None
        self.discriminator = None
        if aws_auth_config is not None:
            self.aws_auth_config = aws_auth_config
        if bearer_token is not None:
            self.bearer_token = bearer_token
        if exec_provider_config is not None:
            self.exec_provider_config = exec_provider_config
        if password is not None:
            self.password = password
        if tls_client_config is not None:
            self.tls_client_config = tls_client_config
        if username is not None:
            self.username = username

    @property
    def aws_auth_config(self):
        """Gets the aws_auth_config of this V1alpha1ClusterConfig.  # noqa: E501


        :return: The aws_auth_config of this V1alpha1ClusterConfig.  # noqa: E501
        :rtype: V1alpha1AWSAuthConfig
        """
        return self._aws_auth_config

    @aws_auth_config.setter
    def aws_auth_config(self, aws_auth_config):
        """Sets the aws_auth_config of this V1alpha1ClusterConfig.


        :param aws_auth_config: The aws_auth_config of this V1alpha1ClusterConfig.  # noqa: E501
        :type: V1alpha1AWSAuthConfig
        """

        self._aws_auth_config = aws_auth_config

    @property
    def bearer_token(self):
        """Gets the bearer_token of this V1alpha1ClusterConfig.  # noqa: E501

        Server requires Bearer authentication. This client will not attempt to use refresh tokens for an OAuth2 flow. TODO: demonstrate an OAuth2 compatible client.  # noqa: E501

        :return: The bearer_token of this V1alpha1ClusterConfig.  # noqa: E501
        :rtype: str
        """
        return self._bearer_token

    @bearer_token.setter
    def bearer_token(self, bearer_token):
        """Sets the bearer_token of this V1alpha1ClusterConfig.

        Server requires Bearer authentication. This client will not attempt to use refresh tokens for an OAuth2 flow. TODO: demonstrate an OAuth2 compatible client.  # noqa: E501

        :param bearer_token: The bearer_token of this V1alpha1ClusterConfig.  # noqa: E501
        :type: str
        """

        self._bearer_token = bearer_token

    @property
    def exec_provider_config(self):
        """Gets the exec_provider_config of this V1alpha1ClusterConfig.  # noqa: E501


        :return: The exec_provider_config of this V1alpha1ClusterConfig.  # noqa: E501
        :rtype: V1alpha1ExecProviderConfig
        """
        return self._exec_provider_config

    @exec_provider_config.setter
    def exec_provider_config(self, exec_provider_config):
        """Sets the exec_provider_config of this V1alpha1ClusterConfig.


        :param exec_provider_config: The exec_provider_config of this V1alpha1ClusterConfig.  # noqa: E501
        :type: V1alpha1ExecProviderConfig
        """

        self._exec_provider_config = exec_provider_config

    @property
    def password(self):
        """Gets the password of this V1alpha1ClusterConfig.  # noqa: E501


        :return: The password of this V1alpha1ClusterConfig.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this V1alpha1ClusterConfig.


        :param password: The password of this V1alpha1ClusterConfig.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def tls_client_config(self):
        """Gets the tls_client_config of this V1alpha1ClusterConfig.  # noqa: E501


        :return: The tls_client_config of this V1alpha1ClusterConfig.  # noqa: E501
        :rtype: V1alpha1TLSClientConfig
        """
        return self._tls_client_config

    @tls_client_config.setter
    def tls_client_config(self, tls_client_config):
        """Sets the tls_client_config of this V1alpha1ClusterConfig.


        :param tls_client_config: The tls_client_config of this V1alpha1ClusterConfig.  # noqa: E501
        :type: V1alpha1TLSClientConfig
        """

        self._tls_client_config = tls_client_config

    @property
    def username(self):
        """Gets the username of this V1alpha1ClusterConfig.  # noqa: E501


        :return: The username of this V1alpha1ClusterConfig.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this V1alpha1ClusterConfig.


        :param username: The username of this V1alpha1ClusterConfig.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1ClusterConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ClusterConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
