# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1ExecProviderConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api_version': 'str',
        'args': 'list[str]',
        'command': 'str',
        'env': 'dict(str, str)',
        'install_hint': 'str'
    }

    attribute_map = {
        'api_version': 'apiVersion',
        'args': 'args',
        'command': 'command',
        'env': 'env',
        'install_hint': 'installHint'
    }

    def __init__(self, api_version=None, args=None, command=None, env=None, install_hint=None):  # noqa: E501
        """V1alpha1ExecProviderConfig - a model defined in Swagger"""  # noqa: E501
        self._api_version = None
        self._args = None
        self._command = None
        self._env = None
        self._install_hint = None
        self.discriminator = None
        if api_version is not None:
            self.api_version = api_version
        if args is not None:
            self.args = args
        if command is not None:
            self.command = command
        if env is not None:
            self.env = env
        if install_hint is not None:
            self.install_hint = install_hint

    @property
    def api_version(self):
        """Gets the api_version of this V1alpha1ExecProviderConfig.  # noqa: E501


        :return: The api_version of this V1alpha1ExecProviderConfig.  # noqa: E501
        :rtype: str
        """
        return self._api_version

    @api_version.setter
    def api_version(self, api_version):
        """Sets the api_version of this V1alpha1ExecProviderConfig.


        :param api_version: The api_version of this V1alpha1ExecProviderConfig.  # noqa: E501
        :type: str
        """

        self._api_version = api_version

    @property
    def args(self):
        """Gets the args of this V1alpha1ExecProviderConfig.  # noqa: E501


        :return: The args of this V1alpha1ExecProviderConfig.  # noqa: E501
        :rtype: list[str]
        """
        return self._args

    @args.setter
    def args(self, args):
        """Sets the args of this V1alpha1ExecProviderConfig.


        :param args: The args of this V1alpha1ExecProviderConfig.  # noqa: E501
        :type: list[str]
        """

        self._args = args

    @property
    def command(self):
        """Gets the command of this V1alpha1ExecProviderConfig.  # noqa: E501


        :return: The command of this V1alpha1ExecProviderConfig.  # noqa: E501
        :rtype: str
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this V1alpha1ExecProviderConfig.


        :param command: The command of this V1alpha1ExecProviderConfig.  # noqa: E501
        :type: str
        """

        self._command = command

    @property
    def env(self):
        """Gets the env of this V1alpha1ExecProviderConfig.  # noqa: E501


        :return: The env of this V1alpha1ExecProviderConfig.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._env

    @env.setter
    def env(self, env):
        """Sets the env of this V1alpha1ExecProviderConfig.


        :param env: The env of this V1alpha1ExecProviderConfig.  # noqa: E501
        :type: dict(str, str)
        """

        self._env = env

    @property
    def install_hint(self):
        """Gets the install_hint of this V1alpha1ExecProviderConfig.  # noqa: E501


        :return: The install_hint of this V1alpha1ExecProviderConfig.  # noqa: E501
        :rtype: str
        """
        return self._install_hint

    @install_hint.setter
    def install_hint(self, install_hint):
        """Sets the install_hint of this V1alpha1ExecProviderConfig.


        :param install_hint: The install_hint of this V1alpha1ExecProviderConfig.  # noqa: E501
        :type: str
        """

        self._install_hint = install_hint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1ExecProviderConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ExecProviderConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
