# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1HostInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'resources_info': 'list[V1alpha1HostResourceInfo]',
        'system_info': 'V1NodeSystemInfo'
    }

    attribute_map = {
        'name': 'name',
        'resources_info': 'resourcesInfo',
        'system_info': 'systemInfo'
    }

    def __init__(self, name=None, resources_info=None, system_info=None):  # noqa: E501
        """V1alpha1HostInfo - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._resources_info = None
        self._system_info = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if resources_info is not None:
            self.resources_info = resources_info
        if system_info is not None:
            self.system_info = system_info

    @property
    def name(self):
        """Gets the name of this V1alpha1HostInfo.  # noqa: E501


        :return: The name of this V1alpha1HostInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1HostInfo.


        :param name: The name of this V1alpha1HostInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def resources_info(self):
        """Gets the resources_info of this V1alpha1HostInfo.  # noqa: E501


        :return: The resources_info of this V1alpha1HostInfo.  # noqa: E501
        :rtype: list[V1alpha1HostResourceInfo]
        """
        return self._resources_info

    @resources_info.setter
    def resources_info(self, resources_info):
        """Sets the resources_info of this V1alpha1HostInfo.


        :param resources_info: The resources_info of this V1alpha1HostInfo.  # noqa: E501
        :type: list[V1alpha1HostResourceInfo]
        """

        self._resources_info = resources_info

    @property
    def system_info(self):
        """Gets the system_info of this V1alpha1HostInfo.  # noqa: E501


        :return: The system_info of this V1alpha1HostInfo.  # noqa: E501
        :rtype: V1NodeSystemInfo
        """
        return self._system_info

    @system_info.setter
    def system_info(self, system_info):
        """Sets the system_info of this V1alpha1HostInfo.


        :param system_info: The system_info of this V1alpha1HostInfo.  # noqa: E501
        :type: V1NodeSystemInfo
        """

        self._system_info = system_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1HostInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1HostInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
