# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1PullRequestGeneratorBitbucket(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'api': 'str',
        'basic_auth': 'V1alpha1BasicAuthBitbucketServer',
        'bearer_token': 'V1alpha1BearerTokenBitbucketCloud',
        'owner': 'str',
        'repo': 'str'
    }

    attribute_map = {
        'api': 'api',
        'basic_auth': 'basicAuth',
        'bearer_token': 'bearerToken',
        'owner': 'owner',
        'repo': 'repo'
    }

    def __init__(self, api=None, basic_auth=None, bearer_token=None, owner=None, repo=None):  # noqa: E501
        """V1alpha1PullRequestGeneratorBitbucket - a model defined in Swagger"""  # noqa: E501
        self._api = None
        self._basic_auth = None
        self._bearer_token = None
        self._owner = None
        self._repo = None
        self.discriminator = None
        if api is not None:
            self.api = api
        if basic_auth is not None:
            self.basic_auth = basic_auth
        if bearer_token is not None:
            self.bearer_token = bearer_token
        if owner is not None:
            self.owner = owner
        if repo is not None:
            self.repo = repo

    @property
    def api(self):
        """Gets the api of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501

        The Bitbucket REST API URL to talk to. If blank, uses https://api.bitbucket.org/2.0.  # noqa: E501

        :return: The api of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :rtype: str
        """
        return self._api

    @api.setter
    def api(self, api):
        """Sets the api of this V1alpha1PullRequestGeneratorBitbucket.

        The Bitbucket REST API URL to talk to. If blank, uses https://api.bitbucket.org/2.0.  # noqa: E501

        :param api: The api of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :type: str
        """

        self._api = api

    @property
    def basic_auth(self):
        """Gets the basic_auth of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501


        :return: The basic_auth of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :rtype: V1alpha1BasicAuthBitbucketServer
        """
        return self._basic_auth

    @basic_auth.setter
    def basic_auth(self, basic_auth):
        """Sets the basic_auth of this V1alpha1PullRequestGeneratorBitbucket.


        :param basic_auth: The basic_auth of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :type: V1alpha1BasicAuthBitbucketServer
        """

        self._basic_auth = basic_auth

    @property
    def bearer_token(self):
        """Gets the bearer_token of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501


        :return: The bearer_token of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :rtype: V1alpha1BearerTokenBitbucketCloud
        """
        return self._bearer_token

    @bearer_token.setter
    def bearer_token(self, bearer_token):
        """Sets the bearer_token of this V1alpha1PullRequestGeneratorBitbucket.


        :param bearer_token: The bearer_token of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :type: V1alpha1BearerTokenBitbucketCloud
        """

        self._bearer_token = bearer_token

    @property
    def owner(self):
        """Gets the owner of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501

        Workspace to scan. Required.  # noqa: E501

        :return: The owner of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this V1alpha1PullRequestGeneratorBitbucket.

        Workspace to scan. Required.  # noqa: E501

        :param owner: The owner of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def repo(self):
        """Gets the repo of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501

        Repo name to scan. Required.  # noqa: E501

        :return: The repo of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :rtype: str
        """
        return self._repo

    @repo.setter
    def repo(self, repo):
        """Sets the repo of this V1alpha1PullRequestGeneratorBitbucket.

        Repo name to scan. Required.  # noqa: E501

        :param repo: The repo of this V1alpha1PullRequestGeneratorBitbucket.  # noqa: E501
        :type: str
        """

        self._repo = repo

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1PullRequestGeneratorBitbucket, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1PullRequestGeneratorBitbucket):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
