# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1SyncWindow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'applications': 'list[str]',
        'clusters': 'list[str]',
        'duration': 'str',
        'kind': 'str',
        'manual_sync': 'bool',
        'namespaces': 'list[str]',
        'schedule': 'str',
        'time_zone': 'str'
    }

    attribute_map = {
        'applications': 'applications',
        'clusters': 'clusters',
        'duration': 'duration',
        'kind': 'kind',
        'manual_sync': 'manualSync',
        'namespaces': 'namespaces',
        'schedule': 'schedule',
        'time_zone': 'timeZone'
    }

    def __init__(self, applications=None, clusters=None, duration=None, kind=None, manual_sync=None, namespaces=None, schedule=None, time_zone=None):  # noqa: E501
        """V1alpha1SyncWindow - a model defined in Swagger"""  # noqa: E501
        self._applications = None
        self._clusters = None
        self._duration = None
        self._kind = None
        self._manual_sync = None
        self._namespaces = None
        self._schedule = None
        self._time_zone = None
        self.discriminator = None
        if applications is not None:
            self.applications = applications
        if clusters is not None:
            self.clusters = clusters
        if duration is not None:
            self.duration = duration
        if kind is not None:
            self.kind = kind
        if manual_sync is not None:
            self.manual_sync = manual_sync
        if namespaces is not None:
            self.namespaces = namespaces
        if schedule is not None:
            self.schedule = schedule
        if time_zone is not None:
            self.time_zone = time_zone

    @property
    def applications(self):
        """Gets the applications of this V1alpha1SyncWindow.  # noqa: E501


        :return: The applications of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: list[str]
        """
        return self._applications

    @applications.setter
    def applications(self, applications):
        """Sets the applications of this V1alpha1SyncWindow.


        :param applications: The applications of this V1alpha1SyncWindow.  # noqa: E501
        :type: list[str]
        """

        self._applications = applications

    @property
    def clusters(self):
        """Gets the clusters of this V1alpha1SyncWindow.  # noqa: E501


        :return: The clusters of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: list[str]
        """
        return self._clusters

    @clusters.setter
    def clusters(self, clusters):
        """Sets the clusters of this V1alpha1SyncWindow.


        :param clusters: The clusters of this V1alpha1SyncWindow.  # noqa: E501
        :type: list[str]
        """

        self._clusters = clusters

    @property
    def duration(self):
        """Gets the duration of this V1alpha1SyncWindow.  # noqa: E501


        :return: The duration of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this V1alpha1SyncWindow.


        :param duration: The duration of this V1alpha1SyncWindow.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def kind(self):
        """Gets the kind of this V1alpha1SyncWindow.  # noqa: E501


        :return: The kind of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this V1alpha1SyncWindow.


        :param kind: The kind of this V1alpha1SyncWindow.  # noqa: E501
        :type: str
        """

        self._kind = kind

    @property
    def manual_sync(self):
        """Gets the manual_sync of this V1alpha1SyncWindow.  # noqa: E501


        :return: The manual_sync of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: bool
        """
        return self._manual_sync

    @manual_sync.setter
    def manual_sync(self, manual_sync):
        """Sets the manual_sync of this V1alpha1SyncWindow.


        :param manual_sync: The manual_sync of this V1alpha1SyncWindow.  # noqa: E501
        :type: bool
        """

        self._manual_sync = manual_sync

    @property
    def namespaces(self):
        """Gets the namespaces of this V1alpha1SyncWindow.  # noqa: E501


        :return: The namespaces of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: list[str]
        """
        return self._namespaces

    @namespaces.setter
    def namespaces(self, namespaces):
        """Sets the namespaces of this V1alpha1SyncWindow.


        :param namespaces: The namespaces of this V1alpha1SyncWindow.  # noqa: E501
        :type: list[str]
        """

        self._namespaces = namespaces

    @property
    def schedule(self):
        """Gets the schedule of this V1alpha1SyncWindow.  # noqa: E501


        :return: The schedule of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this V1alpha1SyncWindow.


        :param schedule: The schedule of this V1alpha1SyncWindow.  # noqa: E501
        :type: str
        """

        self._schedule = schedule

    @property
    def time_zone(self):
        """Gets the time_zone of this V1alpha1SyncWindow.  # noqa: E501


        :return: The time_zone of this V1alpha1SyncWindow.  # noqa: E501
        :rtype: str
        """
        return self._time_zone

    @time_zone.setter
    def time_zone(self, time_zone):
        """Sets the time_zone of this V1alpha1SyncWindow.


        :param time_zone: The time_zone of this V1alpha1SyncWindow.  # noqa: E501
        :type: str
        """

        self._time_zone = time_zone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1SyncWindow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1SyncWindow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
