# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1alpha1ApplicationSourceHelm(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_parameters': 'list[V1alpha1HelmFileParameter]',
        'ignore_missing_value_files': 'bool',
        'parameters': 'list[V1alpha1HelmParameter]',
        'pass_credentials': 'bool',
        'release_name': 'str',
        'skip_crds': 'bool',
        'value_files': 'list[str]',
        'values': 'str',
        'values_object': 'RuntimeRawExtension',
        'version': 'str'
    }

    attribute_map = {
        'file_parameters': 'fileParameters',
        'ignore_missing_value_files': 'ignoreMissingValueFiles',
        'parameters': 'parameters',
        'pass_credentials': 'passCredentials',
        'release_name': 'releaseName',
        'skip_crds': 'skipCrds',
        'value_files': 'valueFiles',
        'values': 'values',
        'values_object': 'valuesObject',
        'version': 'version'
    }

    def __init__(self, file_parameters=None, ignore_missing_value_files=None, parameters=None, pass_credentials=None, release_name=None, skip_crds=None, value_files=None, values=None, values_object=None, version=None):  # noqa: E501
        """V1alpha1ApplicationSourceHelm - a model defined in Swagger"""  # noqa: E501
        self._file_parameters = None
        self._ignore_missing_value_files = None
        self._parameters = None
        self._pass_credentials = None
        self._release_name = None
        self._skip_crds = None
        self._value_files = None
        self._values = None
        self._values_object = None
        self._version = None
        self.discriminator = None
        if file_parameters is not None:
            self.file_parameters = file_parameters
        if ignore_missing_value_files is not None:
            self.ignore_missing_value_files = ignore_missing_value_files
        if parameters is not None:
            self.parameters = parameters
        if pass_credentials is not None:
            self.pass_credentials = pass_credentials
        if release_name is not None:
            self.release_name = release_name
        if skip_crds is not None:
            self.skip_crds = skip_crds
        if value_files is not None:
            self.value_files = value_files
        if values is not None:
            self.values = values
        if values_object is not None:
            self.values_object = values_object
        if version is not None:
            self.version = version

    @property
    def file_parameters(self):
        """Gets the file_parameters of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The file_parameters of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: list[V1alpha1HelmFileParameter]
        """
        return self._file_parameters

    @file_parameters.setter
    def file_parameters(self, file_parameters):
        """Sets the file_parameters of this V1alpha1ApplicationSourceHelm.


        :param file_parameters: The file_parameters of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: list[V1alpha1HelmFileParameter]
        """

        self._file_parameters = file_parameters

    @property
    def ignore_missing_value_files(self):
        """Gets the ignore_missing_value_files of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The ignore_missing_value_files of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: bool
        """
        return self._ignore_missing_value_files

    @ignore_missing_value_files.setter
    def ignore_missing_value_files(self, ignore_missing_value_files):
        """Sets the ignore_missing_value_files of this V1alpha1ApplicationSourceHelm.


        :param ignore_missing_value_files: The ignore_missing_value_files of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: bool
        """

        self._ignore_missing_value_files = ignore_missing_value_files

    @property
    def parameters(self):
        """Gets the parameters of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The parameters of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: list[V1alpha1HelmParameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this V1alpha1ApplicationSourceHelm.


        :param parameters: The parameters of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: list[V1alpha1HelmParameter]
        """

        self._parameters = parameters

    @property
    def pass_credentials(self):
        """Gets the pass_credentials of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The pass_credentials of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: bool
        """
        return self._pass_credentials

    @pass_credentials.setter
    def pass_credentials(self, pass_credentials):
        """Sets the pass_credentials of this V1alpha1ApplicationSourceHelm.


        :param pass_credentials: The pass_credentials of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: bool
        """

        self._pass_credentials = pass_credentials

    @property
    def release_name(self):
        """Gets the release_name of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The release_name of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: str
        """
        return self._release_name

    @release_name.setter
    def release_name(self, release_name):
        """Sets the release_name of this V1alpha1ApplicationSourceHelm.


        :param release_name: The release_name of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: str
        """

        self._release_name = release_name

    @property
    def skip_crds(self):
        """Gets the skip_crds of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The skip_crds of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: bool
        """
        return self._skip_crds

    @skip_crds.setter
    def skip_crds(self, skip_crds):
        """Sets the skip_crds of this V1alpha1ApplicationSourceHelm.


        :param skip_crds: The skip_crds of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: bool
        """

        self._skip_crds = skip_crds

    @property
    def value_files(self):
        """Gets the value_files of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The value_files of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: list[str]
        """
        return self._value_files

    @value_files.setter
    def value_files(self, value_files):
        """Sets the value_files of this V1alpha1ApplicationSourceHelm.


        :param value_files: The value_files of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: list[str]
        """

        self._value_files = value_files

    @property
    def values(self):
        """Gets the values of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The values of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: str
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this V1alpha1ApplicationSourceHelm.


        :param values: The values of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: str
        """

        self._values = values

    @property
    def values_object(self):
        """Gets the values_object of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The values_object of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: RuntimeRawExtension
        """
        return self._values_object

    @values_object.setter
    def values_object(self, values_object):
        """Sets the values_object of this V1alpha1ApplicationSourceHelm.


        :param values_object: The values_object of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: RuntimeRawExtension
        """

        self._values_object = values_object

    @property
    def version(self):
        """Gets the version of this V1alpha1ApplicationSourceHelm.  # noqa: E501


        :return: The version of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1alpha1ApplicationSourceHelm.


        :param version: The version of this V1alpha1ApplicationSourceHelm.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1ApplicationSourceHelm, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ApplicationSourceHelm):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
